# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ProdVec <- function(v1, v2) {
    .Call('flashr_ProdVec', PACKAGE = 'flashr', v1, v2)
}

ProdMat <- function(m1, m2) {
    .Call('flashr_ProdMat', PACKAGE = 'flashr', m1, m2)
}

ashBuild3 <- function(Y, Ef, sigma2_mat) {
    .Call('flashr_ashBuild3', PACKAGE = 'flashr', Y, Ef, sigma2_mat)
}

ashBuild2 <- function(Y, Ef, sigma2_vec, isRow) {
    .Call('flashr_ashBuild2', PACKAGE = 'flashr', Y, Ef, sigma2_vec, isRow)
}

threadcheck <- function(i) {
    .Call('flashr_threadcheck', PACKAGE = 'flashr', i)
}

vec_to_mat <- function(x_) {
    .Call('flashr_vec_to_mat', PACKAGE = 'flashr', x_)
}

SquaredVec <- function(Efac) {
    .Call('flashr_SquaredVec', PACKAGE = 'flashr', Efac)
}

twopi <- function() {
    .Call('flashr_twopi', PACKAGE = 'flashr')
}

ProdVec <- function(E, F) {
    .Call('flashr_ProdVec', PACKAGE = 'flashr', E, F)
}

sumFac <- function(E) {
    .Call('flashr_sumFac', PACKAGE = 'flashr', E)
}

sebeta_const <- function(sigmae2, E) {
    .Call('flashr_sebeta_const', PACKAGE = 'flashr', sigmae2, E)
}

ashBuild3 <- function(Y, Ef, sigma2_mat) {
    .Call('flashr_ashBuild3', PACKAGE = 'flashr', Y, Ef, sigma2_mat)
}

ashBuild1 <- function(Y, Ef, sigma2) {
    .Call('flashr_ashBuild1', PACKAGE = 'flashr', Y, Ef, sigma2)
}

ashBuild2 <- function(Y, Ef, sigma2_vec, isRow) {
    .Call('flashr_ashBuild2', PACKAGE = 'flashr', Y, Ef, sigma2_vec, isRow)
}

threadcheck <- function(i) {
    .Call('flashr_threadcheck', PACKAGE = 'flashr', i)
}

calcLik1 <- function(sigma2v, sigma2_true, n_threads) {
    .Call('flashr_calcLik1', PACKAGE = 'flashr', sigma2v, sigma2_true, n_threads)
}

calcLik2 <- function(sigma2v, sigma2_true, n_threads) {
    .Call('flashr_calcLik2', PACKAGE = 'flashr', sigma2v, sigma2_true, n_threads)
}

calcLik0 <- function(sigma2v, sigma2_true) {
    .Call('flashr_calcLik0', PACKAGE = 'flashr', sigma2v, sigma2_true)
}

rcpparma_hello_world <- function() {
    .Call('flashr_rcpparma_hello_world', PACKAGE = 'flashr')
}

rcpparma_outerproduct <- function(x) {
    .Call('flashr_rcpparma_outerproduct', PACKAGE = 'flashr', x)
}

rcpparma_innerproduct <- function(x) {
    .Call('flashr_rcpparma_innerproduct', PACKAGE = 'flashr', x)
}

rcpparma_bothproducts <- function(x) {
    .Call('flashr_rcpparma_bothproducts', PACKAGE = 'flashr', x)
}

threadcheck <- function(i) {
    .Call('flashr_threadcheck', PACKAGE = 'flashr', i)
}

SquaredVec <- function(Efac) {
    .Call('flashr_SquaredVec', PACKAGE = 'flashr', Efac)
}

SigmaV_Est <- function(Y, El, Ef) {
    .Call('flashr_SigmaV_Est', PACKAGE = 'flashr', Y, El, Ef)
}

SigmaV_Est_2 <- function(Y, El, Ef, El_listed, Ef_listed) {
    .Call('flashr_SigmaV_Est_2', PACKAGE = 'flashr', Y, El, Ef, El_listed, Ef_listed)
}

threadcheck <- function(i) {
    .Call('flashr_threadcheck', PACKAGE = 'flashr', i)
}

SquaredVec <- function(Efac) {
    .Call('flashr_SquaredVec', PACKAGE = 'flashr', Efac)
}

twopi <- function() {
    .Call('flashr_twopi', PACKAGE = 'flashr')
}

ProdVec <- function(E, F) {
    .Call('flashr_ProdVec', PACKAGE = 'flashr', E, F)
}

sumFac <- function(E) {
    .Call('flashr_sumFac', PACKAGE = 'flashr', E)
}

inv_vec <- function(E) {
    .Call('flashr_inv_vec', PACKAGE = 'flashr', E)
}

sebeta_const <- function(sigmae2, E) {
    .Call('flashr_sebeta_const', PACKAGE = 'flashr', sigmae2, E)
}

vec_to_mat <- function(x_) {
    .Call('flashr_vec_to_mat', PACKAGE = 'flashr', x_)
}

ashBuildpool <- function(Y, Ef, sigma2, isRow) {
    .Call('flashr_ashBuildpool', PACKAGE = 'flashr', Y, Ef, sigma2, isRow)
}

ashBuild1 <- function(Y, Ef, sigma2) {
    .Call('flashr_ashBuild1', PACKAGE = 'flashr', Y, Ef, sigma2)
}

ashBuild2 <- function(Y, Ef, sigma2_vec, isRow) {
    .Call('flashr_ashBuild2', PACKAGE = 'flashr', Y, Ef, sigma2_vec, isRow)
}

ashBuild3 <- function(Y, Ef, sigma2_mat) {
    .Call('flashr_ashBuild3', PACKAGE = 'flashr', Y, Ef, sigma2_mat)
}

initval_postprocess1 <- function(Y, El, nonnegative) {
    .Call('flashr_initval_postprocess1', PACKAGE = 'flashr', Y, El, nonnegative)
}

initval_postprocess_fixfactor <- function(Y, fixF, nonnegative) {
    .Call('flashr_initval_postprocess_fixfactor', PACKAGE = 'flashr', Y, fixF, nonnegative)
}

SigmaV_Est <- function(Y, El, Ef) {
    .Call('flashr_SigmaV_Est', PACKAGE = 'flashr', Y, El, Ef)
}

SigmaV_Est_2 <- function(Y, El, Ef, El_listed, Ef_listed) {
    .Call('flashr_SigmaV_Est_2', PACKAGE = 'flashr', Y, El, Ef, El_listed, Ef_listed)
}

calcLik0 <- function(sigma2v, sigma2_true) {
    .Call('flashr_calcLik0', PACKAGE = 'flashr', sigma2v, sigma2_true)
}

mean_mat_rcpp <- function(sigma) {
    .Call('flashr_mean_mat_rcpp', PACKAGE = 'flashr', sigma)
}

rowmeans <- function(X) {
    .Call('flashr_rowmeans', PACKAGE = 'flashr', X)
}

colmeans <- function(X) {
    .Call('flashr_colmeans', PACKAGE = 'flashr', X)
}

